### ISSUE TITLE
The dimension of the picture are ignored

### ISSUE THREAD

**Issue by quadronet** [in2code-de/instagram#11]
Hey, the dimension of the pictures are ignored:
<source srcset="{f:uri.image(src:'/typo3temp/assets/tx_instagram/{image.id}.jpg', width:'200c', height:'200c', fileExtension: 'webp')}" type="image/webp">
<source srcset="{f:uri.image(src:'/typo3temp/assets/tx_instagram/{image.id}.jpg', width:'200c', height:'200c', fileExtension: 'jpg')}" type="image/jpeg">

	<img
										src="{f:uri.image(src:'/typo3temp/assets/tx_instagram/{image.id}.jpg', width:'200c', height:'200c')}"
										title="{image.caption -> f:format.crop(maxCharacters: 120, append: ' ...')}"
										alt="{image.caption -> f:format.crop(maxCharacters: 120, append: ' ...')}"
										loading="lazy" />

All the pictures has the maximum dimension ca. 900px, no cropping..... 

TYPO3 : 10, latest instagram

**Comment by einpraegsam** [comment]
Please check your TYPO3 installation if it is possible to resize images in general.
