### ISSUE TITLE
Local storing of images

### ISSUE THREAD

**Issue by MKmecodia** [in2code-de/instagram#13]
Hello,
set up the extension, everything works great! 
Just one question: How can I store/cache the preview images locally? 
They always seem to link back to instagram. 

Thanks

**Comment by maikschneider** [comment]
The original images are always saved to `typo3temp/assets/tx_instagram/`. If you use the current template file `Resources/Private/Tempaltes/Profile/Show.html` and use the `f:uri.image` viewHelper with adjusted dimensions, the calculated preview / thumbnail images are cached by TYPO3 automatically.

So make sure the images are really stored inside the `typo3temp` dir - maybe there is an issue with write permissions.

**Comment by einpraegsam** [comment]
Thx @maikschneider for helping out. Nothing to add here in my eyes.
Because there is not bug, I will close this issue.

**Comment by MKmecodia** [comment]
I think I found our problem:
The scheduler task instagram:importfeed gets the new posts automatically if we run it with cron job. It does not save the images locally though. It only does so if we run the task manually again. I'm not quite sure how to fix this, maybe you might have some ideas.

**Comment by einpraegsam** [comment]
If it works when started over Apache but not over CLI, maybe rights are missing?
