### ISSUE TITLE
TYPO3 10.4.13 Scheduler Error

### ISSUE THREAD

**Issue by konfuzius** [in2code-de/instagram#2]
`	
Die Ausführung von Task "Konsolenbefehle ausführen (scheduler)" ist fehlgeschlagen mit folgender Meldung: Task failed to execute successfully. Class: TYPO3\CMS\Scheduler\Task\ExecuteSchedulableCommandTask, UID: 8`

Scheduler ausgeführt manuell und via crontab.
Andere Crons via "Konsolenbefehle ausführen (scheduler)" funktionieren bzw. werden ausgeführt.

TYPO3 10.4.13
Instagram 5.1.0
PHP 7.4

**Comment by MacXdk** [comment]
Error: "Field id specified more than once. This is only possible before version 2.1"

Where: /Classes/Domain/Repository/InstagramRepository.php, line 141

Fix: Remove duplicate "id" and "username" from the fields-param

**Comment by einpraegsam** [comment]
Is this fixed?

**Comment by einpraegsam** [comment]
Or on other words. Did you change the code and this fixes the problem? If so, could you please provide a PR or write down here what you have changed?

**Comment by MacXdk** [comment]
This was already fixed on on Apr 13 with commit 02de2c951cf7739ec102e8d786c53830d1ac6c2b
I only told you how to fix. I did not change anything or create a branch. :)

You might want to add one of the two removed id's, if you plan on using it among the other fields. Also _media_ is not used (anymore) as a field-param when fetching IG-media

Line 141 should be:
`
            . '?fields=caption,id,media_type,media_url,permalink,thumbnail_url,timestamp,username,'
`

**Comment by einpraegsam** [comment]
Ok, thx for the final feedback. At the moment I would let it as it is.
Greetings, Alex
