### ISSUE TITLE
v12 Compatibility

### ISSUE THREAD

**Issue by h3nn3s** [in2code-de/instagram#28]
Extension should work with TYPO3 v12 :-)

**Comment by mschwemer** [comment]
There will be an EXT:instagram version, which is compatible with TYPO3 core V12. It is currently under development and testing.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by develth** [comment]
hi @mschwemer 

any news about v12 integration?

Thanks!

**Comment by berndvolke** [comment]
Hello @mschwemer! 

Are there any news concerning the TYPO3 12 compatibility?

Thank U!

**Comment by mschwemer** [comment]
Thanks for your patience

A v12 compatible version is available via the EAP program since 2 weeks.
