### ISSUE TITLE
GDPR opt-in button

### ISSUE THREAD

**Issue by firmenpunkt** [in2code-de/instagram#3]
Hi, Super extension, I could make it run, but is these a way to make it GDPR-conform, like an opt-in button?

**Comment by jhvanderschee** [comment]
If you want a simple and GDPR friendly solution, please try: Please also check: https://www.producthunt.com/posts/ppi-loader. No need to set up developers accounts etc. Just click and go!

**Comment by einpraegsam** [comment]
This extension is absolute GDPR-friendly. Text and all images are stored anonymized on your local server. No need for any buttons that JS-solutions offer.

**Comment by jhvanderschee** [comment]
Okay.. that is great. I see the issue is closed! Good work.
