### ISSUE TITLE
UserId ist converted to float

### ISSUE THREAD

**Issue by cehret** [in2code-de/instagram#5]
When creating a Token the user_id is converted to float.

/Classes/Domain/Repository/InstagramRepository.php -> getShortLiveTokenResult

**Comment by einpraegsam** [comment]
Is this still an issue?

**Comment by cehret** [comment]
Hi Alex,

I provided a pull request: https://github.com/in2code-de/instagram/pull/6

**Comment by einpraegsam** [comment]
Thx, just merged
