### ISSUE TITLE
Can I only access IG Posts from Accounts I own?

### ISSUE THREAD

**Issue by X-Tender** [in2code-de/instagram#7]
Maybe I understand the extension wrong, but I thought that I could post from every (public ) account.
After a successfull test with my private account I changed it to an another username, initiated the post fetch but in the DB were only the posts of my account (under the IG username of the another account).

**Comment by einpraegsam** [comment]
No, Instagram and Facebook API is really a huge overhead. So I'm not totally sure with my answer here. But I think because you have to enable the access in your instagram account, you need admin rights here.
